baseURL: "https://simeonivanov.org"
title: Simeon Ivanov
theme: PaperMod
enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: true
pygmentsUseClasses: true

ignoreLogs: ["warning-goldmark-raw-html"]

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Simeon Ivanov
  description: "This is my personal blog, where I write about the tools, technologies, and practices I explore in my Cloud Native journey — from Kubernetes and Linux internals to Azure, Vim, scripting, and workflow optimization."
  keywords:
    [
      Blog,
      Portfolio,
      CV,
      DevOps,
      Linux,
      Arch Linux,
      Productivity,
      tmux,
      chezmoi,
      gpg,
      neovim,
      CLI,
      Kubernetes,
    ]
  author: Simeon Ivanov
  images: ["https://yourdomain.com/assets/profile.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  profileMode:
    enabled: false
    title: Living on the Command Line
    subtitle: "A place to share my knowledge about Linux and DevOps"
    imageUrl: "https://yourdomain.com/assets/k8s.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: k8s logo
    buttons:
      - name: Blog
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Welcome to my blog!"
    Content: >
      This is where I document my learning journey, tackle technical challenges, and share practical insights.
      From Kubernetes and cloud-native tooling to terminal workflows and note-taking strategies.
      I’ll be sharing my projects and the lessons I learn along the way.

  socialIcons:
    - name: github
      url: "https://github.com/sivanov1994"
    - name: linkedin
      url: "https://www.linkedin.com/in/simeonivanov1994"
    - name: rss
      url: "https://simeonivanov.org/index.xml"

  cover:
    hidden: false
    hiddenInList: false
    hiddenInSingle: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: About
      name: "About"
      url: /aboutme/
      weight: 10
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: "Index"
      name: "Index"
      url: /archives/
      weight: 30
    - identifier: Search
      name: 🔍
      url: /search/
      weight: 50

outputs:
  home:
    - HTML
    - RSS
    - JSON
